// ─── Mock data with realistic SD Digitals business data ──────────────────────
// This provides immediate UI functionality even without a running backend.

const now = new Date();
const d = (offset) => new Date(now.getTime() + offset * 86400000).toISOString();

export const MOCK_EQUIPMENT = [
  { id: 'eq-001', serial_number: 'SNY-FX3-0041',  name: 'Sony FX3 Cinema Rig',                   category: 'Cinema Camera',  brand: 'Sony',              model_number: 'ILME-FX3',    rental_rate_per_day: 185, replacement_value: 3799, status: 'AVAILABLE'      },
  { id: 'eq-002', serial_number: 'DJI-RS3P-0087', name: 'DJI Ronin RS3 Pro Gimbal',              category: 'Stabilizer',     brand: 'DJI',               model_number: 'RS 3 Pro',    rental_rate_per_day: 65,  replacement_value: 849,  status: 'AVAILABLE'      },
  { id: 'eq-003', serial_number: 'APT-600D-0023', name: 'Aputure 600d Light Storm',              category: 'Lighting',       brand: 'Aputure',           model_number: 'LS 600d Pro', rental_rate_per_day: 120, replacement_value: 1699, status: 'OUT_ON_HIRE'    },
  { id: 'eq-004', serial_number: 'ZEN-V3-0012',   name: 'Zhiyun WEEBILL-3S Gimbal',             category: 'Stabilizer',     brand: 'Zhiyun',            model_number: 'WEEBILL-3S',  rental_rate_per_day: 45,  replacement_value: 349,  status: 'AVAILABLE'      },
  { id: 'eq-005', serial_number: 'BMD-PCC6K-009', name: 'Blackmagic Pocket Cinema Camera 6K G2', category: 'Cinema Camera',  brand: 'Blackmagic Design', model_number: 'BMPCC6KG2',   rental_rate_per_day: 145, replacement_value: 1995, status: 'IN_MAINTENANCE' },
  { id: 'eq-006', serial_number: 'RDE-NTG5-0055', name: 'Rode NTG5 Shotgun Microphone Kit',      category: 'Audio',          brand: 'Rode',              model_number: 'NTG5 Kit',    rental_rate_per_day: 35,  replacement_value: 499,  status: 'AVAILABLE'      },
  { id: 'eq-007', serial_number: 'APT-120D-0031', name: 'Aputure NOVA P120c RGBWW Panel',        category: 'Lighting',       brand: 'Aputure',           model_number: 'NOVA P120c',  rental_rate_per_day: 95,  replacement_value: 1299, status: 'RESERVED'       },
  { id: 'eq-008', serial_number: 'DJI-M3E-0018',  name: 'DJI Mavic 3 Enterprise Drone Kit',      category: 'Drone / Aerial', brand: 'DJI',               model_number: 'Mavic 3E',    rental_rate_per_day: 250, replacement_value: 5499, status: 'AVAILABLE'      },
];

export const MOCK_BOOKINGS = [
  {
    booking_id: 'bk-001',
    booking_ref: 'SD-2026-00001',
    status: 'OUT_FOR_DELIVERY',
    customer_name: 'Priya Mehta',
    customer_email: 'priya@luminaryfilms.in',
    customer_company: 'Luminary Films Pvt Ltd',
    equipment_count: 3,
    equipment_preview: ['Sony FX3 Cinema Rig', 'DJI Ronin RS3 Pro Gimbal', 'Rode NTG5 Shotgun Microphone Kit'],
    delivery_address_short: '14, Banjara Hills, Film Nagar, Hyderabad',
    scheduled_delivery_date: d(0),
    scheduled_return_date: d(3),
    driver_assigned: 'Ravi Kumar',
    operational_status: 'EN_ROUTE_DELIVERY',
    created_at: d(-2),
  },
  {
    booking_id: 'bk-002',
    booking_ref: 'SD-2026-00002',
    status: 'CONFIRMED',
    customer_name: 'Arjun Reddy',
    customer_email: 'arjun@redframe.io',
    customer_company: 'RedFrame Studios',
    equipment_count: 2,
    equipment_preview: ['Blackmagic Pocket Cinema Camera 6K G2', 'Aputure NOVA P120c RGBWW Panel'],
    delivery_address_short: '88B, Jubilee Hills Check Post, Hyderabad',
    scheduled_delivery_date: d(2),
    scheduled_return_date: d(5),
    driver_assigned: null,
    operational_status: 'PENDING_DISPATCH',
    created_at: d(-1),
  },
  {
    booking_id: 'bk-003',
    booking_ref: 'SD-2026-00003',
    status: 'AWAITING_PICKUP',
    customer_name: 'Sneha Nair',
    customer_email: 'sneha@cloudninemedia.in',
    customer_company: 'CloudNine Media',
    equipment_count: 2,
    equipment_preview: ['Aputure 600d Light Storm', 'DJI Mavic 3 Enterprise Drone Kit'],
    delivery_address_short: 'Plot 7, HITEC City, Madhapur, Hyderabad',
    scheduled_delivery_date: d(-3),
    scheduled_return_date: d(0),
    driver_assigned: 'Suresh Babu',
    operational_status: 'AWAITING_COLLECTION',
    created_at: d(-5),
  },
  {
    booking_id: 'bk-004',
    booking_ref: 'SD-2026-00004',
    status: 'DRAFT',
    customer_name: 'Vikram Iyer',
    customer_email: 'vikram@indieshoot.co',
    customer_company: 'IndieShoot Collective',
    equipment_count: 1,
    equipment_preview: ['Sony FX3 Cinema Rig'],
    delivery_address_short: '22, Banjara Hills Road No. 12, Hyderabad',
    scheduled_delivery_date: d(7),
    scheduled_return_date: d(10),
    driver_assigned: null,
    operational_status: 'PENDING_DISPATCH',
    created_at: d(-0.5),
  },
  {
    booking_id: 'bk-005',
    booking_ref: 'SD-2026-00005',
    status: 'DELIVERED',
    customer_name: 'Karthik Menon',
    customer_email: 'karthik@pixelyard.in',
    customer_company: 'PixelYard Productions',
    equipment_count: 3,
    equipment_preview: ['DJI Ronin RS3 Pro Gimbal', 'Rode NTG5 Shotgun Microphone Kit', 'Zhiyun WEEBILL-3S Gimbal'],
    delivery_address_short: '9, Kondapur Main Road, Hyderabad',
    scheduled_delivery_date: d(-1),
    scheduled_return_date: d(2),
    driver_assigned: 'Mohammed Aslam',
    operational_status: 'EQUIPMENT_DELIVERED',
    created_at: d(-4),
  },
  {
    booking_id: 'bk-006',
    booking_ref: 'SD-2026-00006',
    status: 'QUOTATION_REQUESTED',
    customer_name: 'Ananya Krishnan',
    customer_email: 'ananya@framebyframe.co',
    customer_company: 'Frame by Frame Studio',
    equipment_count: 4,
    equipment_preview: ['Sony FX3 Cinema Rig', 'Aputure 600d Light Storm', 'Aputure NOVA P120c RGBWW Panel'],
    delivery_address_short: 'Gachibowli, Financial District, Hyderabad',
    scheduled_delivery_date: d(5),
    scheduled_return_date: d(9),
    driver_assigned: null,
    operational_status: 'PENDING_DISPATCH',
    created_at: d(-0.25),
  },
];

export const MOCK_BOOKING_DETAIL = {
  'bk-001': {
    booking_id: 'bk-001',
    booking_ref: 'SD-2026-00001',
    status: 'OUT_FOR_DELIVERY',
    customer: { name: 'Priya Mehta', email: 'priya@luminaryfilms.in', phone: '+91 98765 43210', company: 'Luminary Films Pvt Ltd' },
    creator: { operator_name: 'Dilleswara Rao', operator_email: 'ops@sddigitals.in' },
    equipment: [
      { id: 'eq-001', serial_number: 'SNY-FX3-0041',  name: 'Sony FX3 Cinema Rig',             category: 'Cinema Camera', brand: 'Sony',    rental_rate_per_day: 185, status: 'OUT_ON_HIRE' },
      { id: 'eq-002', serial_number: 'DJI-RS3P-0087', name: 'DJI Ronin RS3 Pro Gimbal',        category: 'Stabilizer',   brand: 'DJI',     rental_rate_per_day: 65,  status: 'OUT_ON_HIRE' },
      { id: 'eq-006', serial_number: 'RDE-NTG5-0055', name: 'Rode NTG5 Shotgun Microphone Kit',category: 'Audio',        brand: 'Rode',    rental_rate_per_day: 35,  status: 'OUT_ON_HIRE' },
    ],
    location: { delivery_address: '14, Banjara Hills, Film Nagar, Hyderabad, Telangana 500034', delivery_lat: 17.4123, delivery_lng: 78.4531, site_contact_name: 'Priya Mehta', site_contact_phone: '+91 98765 43210' },
    scheduled_delivery_date: d(0),
    scheduled_return_date: d(3),
    notes: 'Feature film shoot. Handle with extreme care. Fragile Zeiss lenses in transit. Client requests gear check on arrival.',
    operations_log: {
      log_id: 'ol-001',
      driver_assigned: 'Ravi Kumar',
      driver_phone: '+91 99887 76655',
      vehicle_id: 'TS09EA1234',
      scheduled_pickup_time: d(0),
      scheduled_return_time: d(3),
      actual_delivery_time: null,
      actual_return_time: null,
      operational_status: 'EN_ROUTE_DELIVERY',
      dispatch_notes: 'Fragile equipment — drive carefully. Client confirmed on-site from 09:00.',
    },
    status_history: [
      { from_status: null,                 to_status: 'DRAFT',                changed_by: 'Dilleswara Rao',  changed_at: d(-4), reason: 'Initial booking creation' },
      { from_status: 'DRAFT',              to_status: 'QUOTATION_REQUESTED',  changed_by: 'Dilleswara Rao',  changed_at: d(-3), reason: 'Client requested formal quotation' },
      { from_status: 'QUOTATION_REQUESTED',to_status: 'CONFIRMED',            changed_by: 'Dilleswara Rao',  changed_at: d(-2), reason: 'Deposit received, booking confirmed' },
      { from_status: 'CONFIRMED',          to_status: 'OUT_FOR_DELIVERY',     changed_by: 'Ravi Kumar',      changed_at: d(0),  reason: 'Equipment loaded, departing depot' },
    ],
    active_alerts: [],
    created_at: d(-4),
    updated_at: d(0),
  },
};

export const MOCK_ALERTS = [
  { alert_id: 'al-001', related_entity: 'booking:SD-2026-00003', trigger_type: 'OVERDUE_RETURN',    priority: 'CRITICAL', message: 'Equipment overdue: Aputure 600d Light Storm & DJI Mavic 3E exceeded return window. Contact Sneha Nair immediately.', created_at: d(-0.1) },
  { alert_id: 'al-002', related_entity: 'booking:SD-2026-00002', trigger_type: 'DRIVER_UNASSIGNED', priority: 'HIGH',     message: 'Booking SD-2026-00002 (Arjun Reddy / RedFrame Studios) is CONFIRMED but no driver assigned. Delivery in 2 days.', created_at: d(-0.2) },
  { alert_id: 'al-003', related_entity: 'equipment:BMD-PCC6K-009',trigger_type: 'MAINTENANCE_FLAG', priority: 'MEDIUM',   message: 'Blackmagic BMPCC6K G2 (BMD-PCC6K-009) has a pending maintenance flag. Clear before next allocation.',           created_at: d(-1)   },
];
